WebAplicationShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Services.EntitiesServices.CartServices;
using Services.EntitiesServices.ProductServices;

namespace WebAplicationShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IProductService _productService;
        public CartController(ICartService service,IProductService productService)
        {
            _cartService = service;
            _productService = productService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var carts = await _cartService.GetAllCarts();
            return View(carts);
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int id)
        {
            var item = await _productService.GetCategoryProductById(id);
            return View();
        }

        [HttpPost,ActionName("AddToCart")]
        public async Task<IActionResult> AddToCart(int id,int range)
        {
            if (id != 0)
            {
                await _cartService.AddToCart(id, range);

                return RedirectToAction(nameof(Index));
            }
            return View(id);
        }

    }
}

WebAplicationShop/Controllers/CustomerController.cs
using Domain.EntitesDto;
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Services.EntitiesServices.CustomerService;
using Services.EntitiesServices.OrderServices;
using Services.EntitiesServices.ProductServices;
using Vonage;
using Vonage.Messaging;
using Vonage.Request;

namespace WebAplicationShop.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        public CustomerController(ICustomerService customerService,IProductService productService,IOrderService orderService )
        {
            _customerService = customerService;
            _productService = productService;
            _orderService = orderService;
        }

        public const string v = "ce937fa3";
        public const string VonageApiSecret = "eBIA47occA6Ye4QD";
        private static  Credentials credentials = Credentials.FromApiKeyAndSecret(v, VonageApiSecret);
        public VonageClient client = new VonageClient(credentials);

        public IActionResult Create()
        {
            return View(new Customer());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Customer customer, int Id)
        {
           
            if (ModelState.IsValid)
            {
                customer.Id =0;
                await _customerService.AddCustomer(customer);




                SendSmsRequest? sendSmsRequest=null;
                Product? product = null;

                product = _productService.GetProduct.Where(x => x.Id == Id).FirstOrDefault();
                var getId = _customerService.GetCustomer(customer);
                if (product.Equals(null))
                {
                    ModelState.AddModelError("", "В системе что пошло не так пожолуйста попробуйте позже ?");
                }
                if (product.Category.Name.Equals("Смартфон"))
                {
                    sendSmsRequest = _orderService.AddSmartfonOrder(new OrderDto
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        CustomerId = getId.Id,
                        Price = product.Price,
                        PhoneNumber = customer.PhoneNumber,
                        ProductRange = customer.InstallmentRange,
                        OrderCreated = DateTimeOffset.UtcNow
                    });
                }                
                if (product.Category.Name.Equals("Компьютер"))
                {
                    sendSmsRequest= _orderService.AddKomputerOrder(new OrderDto
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        CustomerId = getId.Id,
                        Price = product.Price,
                        PhoneNumber = customer.PhoneNumber,
                        ProductRange = customer.InstallmentRange,
                        OrderCreated = DateTimeOffset.UtcNow
                    });
                }
                if (product.Category.Name.Equals("Телевизор"))
                {
                    sendSmsRequest= _orderService.AddTvOrder(new OrderDto
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        CustomerId = getId.Id,
                        Price = product.Price,
                        PhoneNumber = customer.PhoneNumber,
                        ProductRange = customer.InstallmentRange,
                        OrderCreated = DateTimeOffset.UtcNow
                    });
                }


                if (sendSmsRequest != null)
                {
                    try
                    {
                        SendSmsResponse smsResponse = client.SmsClient.SendAnSms(sendSmsRequest);
                        ViewBag.MessageId = smsResponse.Messages[0].MessageId;
                    }
                    catch (VonageSmsResponseException ex)
                    {
                        ViewBag.Error = ex.Message;
                    }
                }


                
                return RedirectToAction("Complete");
           }
            return View(customer);
            

        }
      
        public IActionResult Complete()
        {
            return View();
        }

       
    }
}

WebAplicationShop/Controllers/OrderController.cs
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Services.EntitiesServices.OrderServices;

namespace WebAplicationShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
               _orderService = orderService;
        }
        
        [HttpGet]
        public IActionResult AddToOrder()
        {
            return View(new Customer());
        }

        [HttpPost]
        public async Task<IActionResult> AddToOrder(Customer customer)
        {
            if (ModelState.IsValid)
            {
                await _orderService.AddToOrder(customer);

                return RedirectToAction(nameof(Result));
            }

            return View(customer);
        }
        [HttpPost]
        public IActionResult Result()
        {
            return View();
        }
    }
}

WebAplicationShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Services.EntitiesServices.ProductServices;

namespace WebAplicationShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var products = await _productService.GetProductsByJoinCategories();
       
          /* var items =products.Join(_categoryService.GetCategories,
                                   product => product.CategoryId,
                                   category => category.Id,
                                   (product, category)
                                    => new GetProductsByJoinCategories
                                    {
                                        Id = product.Id,
                                        Name = product.Name,
                                        Price = product.Price,
                                        Image = product.Image,
                                        CategoryName = category.Name,
                                        Description = category.Description
                                    }).ToListAsync();*/
            return View(products);
        }
      
    }
}

WebAplicationShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Administration</title>

    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <img src="assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">Admin</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->



                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>Tajiev Olimjon</h6>
                            <span>.Net developer</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                <i class="bi bi-person"></i>
                                <span>Мой профиль</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                <i class="bi bi-gear"></i>
                                <span>Настройки учетной записи</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Нужна помощь?</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Выход</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="index.html">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Товары</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Admin" asp-controller="Product" asp-action="Index">
                            <i class="bi bi-circle"></i><span>Все товары</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Product" asp-action="Create">
                            <i class="bi bi-circle"></i><span>Добавить</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Components Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-journal-text"></i><span>Категории</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Admin" asp-controller="Category" asp-action="Index">
                            <i class="bi bi-circle"></i><span>Все категории</span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Category" asp-action="Create">
                            <i class="bi bi-circle"></i><span>Добавить</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Forms Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-layout-text-window-reverse"></i><span>Заказы</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Admin" asp-controller="Order" asp-action="Index">
                            <i class="bi bi-circle"></i><span>Все заказы</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Tables Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-bar-chart"></i><span>Клиенты</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Admin" asp-controller="Customer" asp-action="Index">
                            <i class="bi bi-circle"></i><span>Все клиенты</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Charts Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-gem"></i><span>Корзина</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a asp-area="Admin" asp-controller="Cart" asp-action="Index">
                            <i class="bi bi-circle"></i><span>Все данные в корзине</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Icons Nav -->

            <li class="nav-heading">Pages</li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="users-profile.html">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-faq.html">
                    <i class="bi bi-question-circle"></i>
                    <span>F.A.Q</span>
                </a>
            </li><!-- End F.A.Q Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-contact.html">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li><!-- End Contact Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-register.html">
                    <i class="bi bi-card-list"></i>
                    <span>Register</span>
                </a>
            </li><!-- End Register Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-login.html">
                    <i class="bi bi-box-arrow-in-right"></i>
                    <span>Login</span>
                </a>
            </li><!-- End Login Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-error-404.html">
                    <i class="bi bi-dash-circle"></i>
                    <span>Error 404</span>
                </a>
            </li><!-- End Error 404 Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="pages-blank.html">
                    <i class="bi bi-file-earmark"></i>
                    <span>Blank</span>
                </a>
            </li><!-- End Blank Page Nav -->

        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">

        <!-- <div class="pagetitle">
          <h1>Dashboard</h1>
          <nav>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </nav>
        </div>End Page Title -->
        @RenderBody()

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebShopFurniture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.min.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <!-- <script src="assets/vendor/php-email-form/validate.js"></script> -->
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

  </body>

</html>